//------------------------------------------------------------------------------
// <auto-generated class>
//     This code was generated by Ubiq Mobile plug-in.
//
//     You can modify this source
//     This class contains message for information exchange between service and client apps
// </auto-generated class>
//------------------------------------------------------------------------------

using Ubiq.InterfaceAPI;

namespace ServiceDemo
{
    public enum MessageType
    {
        None,
        DataUpdated,
        IncData,
        Init,// first message for subscribe to changes from another already existing clients
    }

    // Message for information exchange between service and client apps.
    internal class ServiceDemoMessageType : IntMessage
    {
        public MessageType MessageType;
        public uint ClientId;

        public int Value;

        public ServiceDemoMessageType(uint clientID, MessageType messageType)
        {
            ClientId = clientID;
            MessageType = messageType;
        }
    }
}
