//------------------------------------------------------------------------------
// <auto-generated class>
//     This code was generated by Ubiq Mobile plug-in.
//
//	   This is API of our service.
//     You can modify this source
//     It will be used by client apps to talk to service
// </auto-generated class>
//------------------------------------------------------------------------------

using Ubiq.Subcore;
using Ubiq.InterfaceAPI;

namespace ServiceDemo
{
    public delegate void DataUpdate(int i);

    // This is API of our service.
    // It will be used by client apps to talk to service.
    public class ServiceDemoApiName : BaseAPI
    {
        public event DataUpdate DataUpdated;

        public void InitAPI()
        {
            subscribeInterface.Send(new ServiceDemoMessageType(App.ClientID, MessageType.Init));
        }

        public void TestAPI()
        {
            subscribeInterface.Send(new ServiceDemoMessageType(App.ClientID, MessageType.IncData));
        }

        // Base class constructor initializes SubscribeInterface we will use to communicate our service.
        public ServiceDemoApiName(MApp app)
            : base(app, ServiceDemo.ServiceName)
        {
            subscribeInterface.MessageReceived += subscribeInterface_MessageReceived;
        }

        void subscribeInterface_MessageReceived(UbiqInterface sender, System.EventArgs<IntMessage> e)
        {
            var msg = e.Value as ServiceDemoMessageType;
            if (msg == null)
            {
                return;
            }
            if (msg.MessageType == MessageType.DataUpdated)
            {
                if (DataUpdated != null)
                {
                    DataUpdated(msg.Value);
                }
            }
        }
    }
}





